MOV DPTR,#0000H
MOVX A,@DPTR
MOV 30H,A
MOV 28H,A
MOV R7,#05H
INC DPL
LOOP: MOVX A,@DPTR
      CJNE A,28H,MIN
MIN:  JNC NEXT
      MOV 28H,A
      SJMP DOWN
NEXT: CJNE A,30H,MAX
MAX:  JC DOWN
      MOV 30H,A
DOWN: INC DPL
      DJNZ R7,LOOP
MOV DPTR,#0010H
MOV A,28H
MOVX @DPTR,A
MOV DPTR,#0011H
MOV A,30H
MOVX @DPTR,A
STOP: SJMP STOP